Need to get this up. Deprecating the NatveLands route temporarily
There's something erroring out in the landing page route for native lands.

The message seems clear:

```
TypeError: Cannot read properties of undefined (reading 'ok')
```

So it's the response from the `fetch()` call in `landing.js` that's causing it. I can't fix it right now.